### ISSUE TITLE
Remove / replace inherited_resources

### ISSUE THREAD

**Issue by jvdp** [brightin/brightcontent#22]
The gem is deprecated: https://github.com/josevalim/inherited_resources#deprecation-notice. (I also find the extra levels of indirection pretty annoying, eg. if you want to find the implementation of the default actions.)

It should be easy to implement the basic actions generically ourselves (similar to the old `DefaultAction` module but perhaps a bit cleaner.) I think perhaps we should give up the support for nesting though, and it's something that you can (should?) setup easily per project.

Any thoughts?

**Comment by jvdp** [comment]
Some preliminary work here: https://github.com/jvdp/brightcontent/tree/remove-inherited-resources

**Comment by jvdp** [comment]
@stefanroex you tested my branch right? Any news?

**Comment by stefanroex** [comment]
Unfortunately, I haven't... :crying_cat_face:

**Comment by jvdp** [comment]
Closing in favor of #46
