### ISSUE TITLE
Allow arbitrary filter field names

### ISSUE THREAD

**Issue by s-andringa** [brightin/brightcontent#36]
Currently only attribute-, and belongs-to association names are accepted by `FilterField`. [Here](https://github.com/brightin/brightcontent/blob/master/core/lib/brightcontent/view_lookup/filter_field.rb#L5) an exception is raised if a name does not comply with this rule.

I assume this rule was enforced to ensure a sensible list of filter options could be constructed.

With the introduction of filter field options in 4519e1f0f760e5e50742463e8572cef3f5bdb7c6 this argument does not hold up any longer. We could now default to a string type filter for unknown fields. This would allow for a lot more flexibility as more Ransack power can be harnessed. Some examples:

```ruby
class BlogsController < Brightcontent::BaseController

  # Filter by multiple attributes:
  filter_fields :name_or_description

  # Filter by has_many relations:
  filter_fields categories_id: { as: :select, collection: ->{ Category.all } }

  # Or both:
  filter_fields :name_or_categories_name

  private

  def end_of_association_chain
    super.includes(:categories)
  end
end
```

I'd be happy to make this happen. Just wanted to check with you if my assumption is right, or if maybe there are more reasons for restricting filter fields to attributes and belongs-to relations...

**Comment by jvdp** [comment]
Your assumption is right, so :+1:
