### ISSUE TITLE
Rails-4-2 dependant on inherited_resources gem

### ISSUE THREAD

**Issue by kaibakker** [brightin/brightcontent#38]
When using the rails-4-2 branch, I get this error:
```
bundler/gems/brightcontent-b4f73a5772e4/core/lib/brightcontent/core.rb:9:in `require': cannot load such file -- inherited_resources (LoadError)
```

adding `gem 'inherited_resources'` fixes this, so this dependancy should be added

**Comment by stefanroex** [comment]
I noticed that `inherited_resources` *does* support Rails 4.2 right now. So you're totally right!

At the time the rails-4-2 branch was created, the stable version of `inherted_resoures` didn't have 4.2 support. We were forced to use a git branch as dependency, which cannot be used as a dependency in the gemspec.

Expect a new gem-release with 4.2 support next week.

**Comment by jvdp** [comment]
So it took a bit longer but BrightContent 2.2.0 supports Rails 4.2: https://rubygems.org/gems/brightcontent
