### ISSUE TITLE
Fixnum deprecation warning on pagination

### ISSUE THREAD

**Issue by martijnbleeker** [brightin/brightcontent#53]
The `will_paginate-bootstrap` gem is no longer maintained and the readme mentions no PRs are accepted anymore. However, it causes a `Fixnum` deprecation warning when a paginated index page is loaded.

`~/.gem/ruby/2.4.1/gems/will_paginate-bootstrap-1.0.1/lib/bootstrap_pagination/bootstrap_renderer.rb:11: warning: constant ::Fixnum is deprecated`

This [PR](https://github.com/bootstrap-ruby/will_paginate-bootstrap/pull/51) solves the issue, but as mentioned before, the maintainer no longer accepts PRs.

**Comment by wvengen** [comment]
Perhaps [bootstrap-will_paginate](https://github.com/yrgoldteeth/bootstrap-will_paginate) would be an option?

**Comment by jvdp** [comment]
Fixed in 2.5.0!
