### ISSUE TITLE
Sass-rails dependency soon to be deprecated

### ISSUE THREAD

**Issue by wvengen** [brightin/brightcontent#55]
When updating gems, I get a warning:

> Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
> 
> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
>   primary implementation: https://sass-lang.com/install
> 
> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
>   sassc gem: https://github.com/sass/sassc-ruby#readme
> 
> * For more details, please refer to the Sass blog:
>   http://sass.logdown.com/posts/7081811

See also https://github.com/rails/sass-rails/issues/420.

Brightcontent [depends on `sass-rails`](https://github.com/brightin/brightcontent/blob/5ee51fded9f7cc0789b85008015f5896964b017b/core/brightcontent-core.gemspec#L25), which will be deprecated very soon. Let's move to `sassc-rails` instead.

**Comment by jvdp** [comment]
Good idea! Do you know if there's an impact on the existing code or can we just upgrade without other changes?

**Comment by wvengen** [comment]
In other code I've upgraded without changes.

**Comment by jvdp** [comment]
@wvengen you can upgrade to 2.5.1 for this :)

**Comment by wvengen** [comment]
Thank you! :tada:
